# Generated by Django 2.1.1 on 2018-09-20 11:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 20, 11, 16, 52, 896918, tzinfo=utc)),
        ),
    ]
